/*
 * Copyright 2019 EPAM Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.epam.daggerbinds.processor

object SourceCode {
    const val generatedClassQualifierName = "com.epam.daggerbinds.bindto.Generated_BindsModule"

    object MultiSubtypes {
        object NamedQualifier {
            const val generatedClass = """
            package com.epam.daggerbinds.bindto;

            import com.epam.subtypes.severalfirst.Repository;
            import com.epam.subtypes.severalfirst.RepositoryImpFirst;
            import com.epam.subtypes.severalfirst.RepositoryImpSecond;
            import dagger.Binds;
            import dagger.Module;
            import javax.inject.Named;
            /**
             * Generated by dagger-binds-generator
             * 17-June-2019 14:20
             */
            @Module
            public interface Generated_BindsModule {
              @Binds
              @Named("com.epam.subtypes.severalfirst.RepositoryImpFirst")
              Repository binds_com_epam_subtypes_severalfirst_RepositoryImpFirst(
                  RepositoryImpFirst com_epam_subtypes_severalfirst_RepositoryImpFirst);

              @Binds
              @Named("com.epam.subtypes.severalfirst.RepositoryImpSecond")
              Repository binds_com_epam_subtypes_severalfirst_RepositoryImpSecond(
                  RepositoryImpSecond com_epam_subtypes_severalfirst_RepositoryImpSecond);
            """

            const val superClassQualifierName = "com.epam.subtypes.severalfirst.Repository"
            const val superClass = """
            package com.epam.subtypes.severalfirst;
            public interface Repository {
            }
            """

            const val impClassFirstQualifierName = "com.epam.subtypes.severalfirst.RepositoryImpFirst"
            const val impClassFirst = """
            package com.epam.subtypes.severalfirst;
            import com.epam.daggerbinds.annotation.BindTo;
            import javax.inject.Named;
            @BindTo(interfaceType = Repository.class, qualifier = Named.class)
            public class RepositoryImpFirst implements Repository {
            }
            """

            const val impClassSecondQualifierName = "com.epam.subtypes.severalfirst.RepositoryImpSecond"
            const val impClassSecond = """
            package com.epam.subtypes.severalfirst;
            import com.epam.daggerbinds.annotation.BindTo;
            import javax.inject.Named;
            @BindTo(interfaceType = Repository.class, qualifier = Named.class)
            public class RepositoryImpSecond implements Repository {
            }
            """
        }

        object CustomQualifier {
            const val generatedClass = """
                package com.epam.daggerbinds.bindto;

                import com.epam.subtypes.severalfirst.Service;
                import com.epam.subtypes.severalfirst.ServiceImpFirst;
                import com.epam.subtypes.severalfirst.ServiceImpQFirst;
                import com.epam.subtypes.severalfirst.ServiceImpQSecond;
                import com.epam.subtypes.severalfirst.ServiceImpSecond;
                import dagger.Binds;
                import dagger.Module;

                /**
                 * Generated by dagger-binds-generator
                 * 17-June-2019 14:41
                 */
                @Module
                public interface Generated_BindsModule {
                    @Binds
                    @ServiceImpQFirst
                    Service binds_com_epam_subtypes_severalfirst_ServiceImpFirst(
                    ServiceImpFirst com_epam_subtypes_severalfirst_ServiceImpFirst);

                    @Binds
                    @ServiceImpQSecond
                    Service binds_com_epam_subtypes_severalfirst_ServiceImpSecond(
                    ServiceImpSecond com_epam_subtypes_severalfirst_ServiceImpSecond);
                }
            """

            const val superClassQualifierName = "com.epam.subtypes.severalfirst.Service"
            const val superClass = """
                package com.epam.subtypes.severalfirst;
                public interface Service {
                }
            """

            const val impClassFirstQualifierName = "com.epam.subtypes.severalfirst.ServiceImpFirst"
            const val impClassFirst = """
                package com.epam.subtypes.severalfirst;
                import com.epam.subtypes.severalfirst.ServiceImpQFirst;
                import com.epam.daggerbinds.annotation.BindTo;
                @BindTo(interfaceType = Service.class, qualifier = ServiceImpQFirst.class)
                public class ServiceImpFirst implements Service {
                }
            """

            const val impClassSecondQualifierName = "com.epam.subtypes.severalfirst.ServiceImpSecond"
            const val impClassSecond = """
                package com.epam.subtypes.severalfirst;
                import com.epam.subtypes.severalfirst.ServiceImpQSecond;
                import com.epam.daggerbinds.annotation.BindTo;
                @BindTo(interfaceType = Service.class, qualifier = ServiceImpQSecond.class)
                public class ServiceImpSecond implements Service {
                }
            """

            const val customQualifierClassFirstQualifierName = "com.epam.subtypes.severalfirst.ServiceImpQFirst"
            const val customQualifierClassFirst = """
                package com.epam.subtypes.severalfirst;
                import javax.inject.Qualifier;
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                @Qualifier
                @Retention(RetentionPolicy.RUNTIME)
                public @interface ServiceImpQFirst {
                }
            """

            const val customQualifierClassSecondQualifierName = "com.epam.subtypes.severalfirst.ServiceImpQSecond"
            const val customQualifierClassSecond = """
                package com.epam.subtypes.severalfirst;
                import javax.inject.Qualifier;
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                @Qualifier
                @Retention(RetentionPolicy.RUNTIME)
                public @interface ServiceImpQSecond {
                }
            """
        }
    }

    object SingleSubtype {
        const val generatedClass = """
            package com.epam.daggerbinds.bindto;

            import com.epam.subtypes.single.Service;
            import com.epam.subtypes.single.ServiceImp;
            import dagger.Binds;
            import dagger.Module;

            /**
            * Generated by dagger-binds-generator
            * 13-June-2019 16:34
            */
            @Module
            public interface Generated_BindsModule {
            @Binds
            Service binds_com_epam_subtypes_single_ServiceImp(ServiceImp com_epam_subtypes_single_ServiceImp);
            }
            """

        const val superClassQualifierName = "com.epam.subtypes.single.Service"
        const val superClass = """
            package com.epam.subtypes.single;
            public interface Service {
            }
            """

        const val impClassQualifierName = "com.epam.subtypes.single.ServiceImp"
        const val impClass = """
            package com.epam.subtypes.single;
            import com.epam.daggerbinds.annotation.BindTo;
            import com.epam.subtypes.single.Service;
            @BindTo(interfaceType = Service.class)
            public class ServiceImp implements Service {
            }
            """
    }

    object WithError {
        object NoQualifier{
            const val superClassQualifierName = "com.epam.subtypes.severalfirst.Repository"
            const val superClass = """
            package com.epam.subtypes.severalfirst;
            public interface Repository {
            }
            """

            const val impClassFirstQualifierName = "com.epam.subtypes.severalfirst.RepositoryImpFirst"
            const val impClassFirst = """
            package com.epam.subtypes.severalfirst;
            import com.epam.daggerbinds.annotation.BindTo;
            @BindTo(interfaceType = Repository.class)
            public class RepositoryImpFirst implements Repository {
            }
            """

            const val impClassSecondQualifierName = "com.epam.subtypes.severalfirst.RepositoryImpSecond"
            const val impClassSecond = """
            package com.epam.subtypes.severalfirst;
            import com.epam.daggerbinds.annotation.BindTo;
            @BindTo(interfaceType = Repository.class)
            public class RepositoryImpSecond implements Repository {
            }
            """
        }
        object NoInterface{
            const val superClassQualifierName = "com.epam.subtypes.severalfirst.Repository"
            const val superClass = """
            package com.epam.subtypes.severalfirst;
            public interface Repository {
            }
            """

            const val impClassQualifierName = "com.epam.subtypes.severalfirst.RepositoryImp"
            const val impClass = """
            package com.epam.subtypes.severalfirst;
            import com.epam.daggerbinds.annotation.BindTo;
            @BindTo(interfaceType = Repository.class)
            public class RepositoryImp {
            }
            """
        }
        object InterfaceTypeIsQualifier{
            const val superClassQualifierName = "com.epam.subtypes.severalfirst.Repository"
            const val superClass = """
            package com.epam.subtypes.severalfirst;
            public interface Repository {
            }
            """

            const val impClassQualifierName = "com.epam.subtypes.severalfirst.RepositoryImp"
            const val impClass = """
            package com.epam.subtypes.severalfirst;
            import com.epam.daggerbinds.annotation.BindTo;
            import javax.inject.Named;
            @BindTo(interfaceType = Named.class)
            public class RepositoryImp implements Repository {
            }
            """
        }

        object QualifierIsNotQualifier{
            const val superClassQualifierName = "com.epam.subtypes.severalfirst.Repository"
            const val superClass = """
            package com.epam.subtypes.severalfirst;
            public interface Repository {
            }
            """

            const val impClassQualifierName = "com.epam.subtypes.severalfirst.RepositoryImp"
            const val impClass = """
            package com.epam.subtypes.severalfirst;
            import com.epam.daggerbinds.annotation.BindTo;
            @BindTo(interfaceType = Repository.class, qualifier = Repository.class)
            public class RepositoryImp implements Repository {
            }
            """
        }
    }
}